# Generated by Django 5.2.12 on 2026-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
